apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mwve34zx5-python
  janus-idp.io/tekton: mwve34zx5-python
  backstage.io/kubernetes-id: mwve34zx5-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mwve34zx5-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
